In [219]:
#Solution Q1. Create a new attribute called 'Tag' and it should contain the letters between (*) from  'Country'
import re
import numpy as np
import pandas as pd
#how to rename columns and/or skip rows that we don't want to consider
#loading our data
olympics_df = pd.read_csv('olympics.csv', header=1)
new_names =  {'Unnamed: 0': 'Country',
              '? Summer': 'Summer Olympics',
              '01 !': 'Gold',
              '02 !': 'Silver',
              '03 !': 'Bronze',
              '? Winter': 'Winter Olympics',
              '01 !.1': 'Gold.1',
              '02 !.1': 'Silver.1',
              '03 !.1': 'Bronze.1',
              '? Games': '# Games',
              '01 !.2': 'Gold.2',
              '02 !.2': 'Silver.2',
              '03 !.2': 'Bronze.2'}
olympics_df.rename(columns=new_names, inplace=True)#our new names
olympics_df.rename(columns={'Country':'Tag'}, inplace=True)
#again strings are a problem for us
#this functions will help us to extract the city-state of our region name
#create another function to retrieve the Universty Name and add a new atribute to towns_df

olympics_df['Tag']=olympics_df['Tag'].str.findall(r"\(\w{3}\)")

dd=olympics_df['Tag'].str[0]
dd=dd.str[1:-1]
olympics_df["Tag"]=pd.DataFrame(dd)
olympics_df1=olympics_df
olympics_df1

,Tag,Summer Olympics,Gold,Silver,Bronze,Total,Winter Olympics,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
0,AFG,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,ALG,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,ARG,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,ARM,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
4,ANZ,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
5,AUS,25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
6,AUT,26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
7,AZE,5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
8,BAH,15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
9,BRN,8,0,0,1,1,0,0,0,0,0,8,0,0,1,1
10,BAR,11,0,0,1,1,0,0,0,0,0,11,0,0,1,1
11,BLR,5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
12,BEL,25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
13,BER,17,0,0,1,1,7,0,0,0,0,24,0,0,1,1
14,BOH,3,0,1,3,4,0,0,0,0,0,3,0,1,3,4
15,BOT,9,0,1,0,1,0,0,0,0,0,9,0,1,0,1
16,BRA,21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
17,BWI,1,0,0,2,2,0,0,0,0,0,1,0,0,2,2
18,BUL,19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
19,BDI,5,1,0,0,1,0,0,0,0,0,5,1,0,0,1
20,CMR,13,3,1,1,5,1,0,0,0,0,14,3,1,1,5
21,CAN,25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
22,CHI,22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
23,CHN,9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
24,COL,18,2,6,11,19,1,0,0,0,0,19,2,6,11,19
25,CRC,14,1,1,2,4,6,0,0,0,0,20,1,1,2,4
26,CIV,12,0,1,0,1,0,0,0,0,0,12,0,1,0,1
27,CRO,6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
28,CUB,19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
29,CYP,9,0,1,0,1,10,0,0,0,0,19,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,SRI,16,0,2,0,2,0,0,0,0,0,16,0,2,0,2
118,SUD,11,0,1,0,1,0,0,0,0,0,11,0,1,0,1
119,SUR,11,1,0,1,2,0,0,0,0,0,11,1,0,1,2
120,SWE,26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
121,SUI,27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
122,SYR,12,1,1,1,3,0,0,0,0,0,12,1,1,1,3
123,TPE,13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
124,TJK,5,0,1,2,3,4,0,0,0,0,9,0,1,2,3
125,TAN,12,0,2,0,2,0,0,0,0,0,12,0,2,0,2
126,THA,15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
127,TOG,9,0,0,1,1,1,0,0,0,0,10,0,0,1,1
128,TGA,8,0,1,0,1,1,0,0,0,0,9,0,1,0,1
129,TRI,16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
130,TUN,13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
131,TUR,21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
132,UGA,14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
133,UKR,5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
134,UAE,8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
135,USA,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
136,URU,20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
137,UZB,5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
138,VEN,17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
139,VIE,14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
140,ISV,11,0,1,0,1,7,0,0,0,0,18,0,1,0,1
141,YUG,16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
142,IOP,1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
143,ZAM,12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
144,ZIM,12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
145,ZZX,3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
146,NaN,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [298]:
#Solution Q2. Alter the values of 'Country' so it just contains the actual names of the countries
import re
import numpy as np
import pandas as pd

#how to rename columns and/or skip rows that we don't want to consider
#loading our data
olympics_df = pd.read_csv('olympics.csv',header=1)
new_names =  {'Unnamed: 0': 'Country','? Summer': 'Summer Olympics','01 !': 'Gold','02 !': 'Silver','03 !': 'Bronze',
              '? Winter': 'Winter Olympics','01 !.1': 'Gold.1','02 !.1': 'Silver.1','03 !.1': 'Bronze.1','? Games': '# Games',
              '01 !.2': 'Gold.2','02 !.2': 'Silver.2','03 !.2': 'Bronze.2'}
olympics_df.rename(columns=new_names, inplace=True)#our new names
olympics_df.head()

c = []
for i in range (0, len(olympics_df)):
    c.append(olympics_df['Country'][i].split(" ")[0])
c
olympics_df['Country']=pd.DataFrame(c)
olympics_df

,Country,Summer Olympics,Gold,Silver,Bronze,Total,Winter Olympics,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
0,Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
4,Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
5,Australia,25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
6,Austria,26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
7,Azerbaijan,5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
8,Bahamas,15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
9,Bahrain,8,0,0,1,1,0,0,0,0,0,8,0,0,1,1
10,Barbados,11,0,0,1,1,0,0,0,0,0,11,0,0,1,1
11,Belarus,5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
12,Belgium,25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
13,Bermuda,17,0,0,1,1,7,0,0,0,0,24,0,0,1,1
14,Bohemia,3,0,1,3,4,0,0,0,0,0,3,0,1,3,4
15,Botswana,9,0,1,0,1,0,0,0,0,0,9,0,1,0,1
16,Brazil,21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
17,British,1,0,0,2,2,0,0,0,0,0,1,0,0,2,2
18,Bulgaria,19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
19,Burundi,5,1,0,0,1,0,0,0,0,0,5,1,0,0,1
20,Cameroon,13,3,1,1,5,1,0,0,0,0,14,3,1,1,5
21,Canada,25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
22,Chile,22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
23,China,9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
24,Colombia,18,2,6,11,19,1,0,0,0,0,19,2,6,11,19
25,Costa,14,1,1,2,4,6,0,0,0,0,20,1,1,2,4
26,Ivory,12,0,1,0,1,0,0,0,0,0,12,0,1,0,1
27,Croatia,6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
28,Cuba,19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
29,Cyprus,9,0,1,0,1,10,0,0,0,0,19,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,Sri,16,0,2,0,2,0,0,0,0,0,16,0,2,0,2
118,Sudan,11,0,1,0,1,0,0,0,0,0,11,0,1,0,1
119,Suriname,11,1,0,1,2,0,0,0,0,0,11,1,0,1,2
120,Sweden,26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
121,Switzerland,27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
122,Syria,12,1,1,1,3,0,0,0,0,0,12,1,1,1,3
123,Chinese,13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
124,Tajikistan,5,0,1,2,3,4,0,0,0,0,9,0,1,2,3
125,Tanzania,12,0,2,0,2,0,0,0,0,0,12,0,2,0,2
126,Thailand,15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
127,Togo,9,0,0,1,1,1,0,0,0,0,10,0,0,1,1
128,Tonga,8,0,1,0,1,1,0,0,0,0,9,0,1,0,1
129,Trinidad,16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
130,Tunisia,13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
131,Turkey,21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
132,Uganda,14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
133,Ukraine,5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
134,United,8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
135,United,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
136,Uruguay,20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
137,Uzbekistan,5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
138,Venezuela,17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
139,Vietnam,14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
140,Virgin,11,0,1,0,1,7,0,0,0,0,18,0,1,0,1
141,Yugoslavia,16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
142,Independent,1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
143,Zambia,12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
144,Zimbabwe,12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
145,Mixed,3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
146,Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [301]:
#Solution Q3 Create a new dataframe only containing only the following attributes: 'Tag', 'summer olympics' and 'winter olympics'.
 #3.1. In addition, it should also contain 'combined Total', which has to be calculated using the sum of 'summmer olympics' and 'winter olympics'
import re   
import numpy as np
import pandas as pd
#how to rename columns and/or skip rows that we don't want to consider
#loading our data
olympics_df = pd.read_csv('olympics.csv', header=1)
new_names =  {'Unnamed: 0': 'Country',
              '? Summer': 'Summer Olympics',
              '01 !': 'Gold',
              '02 !': 'Silver',
              '03 !': 'Bronze',
              '? Winter': 'Winter Olympics',
              '01 !.1': 'Gold.1',
              '02 !.1': 'Silver.1',
              '03 !.1': 'Bronze.1',
              '? Games': '# Games',
              '01 !.2': 'Gold.2',
              '02 !.2': 'Silver.2',
              '03 !.2': 'Bronze.2'}
olympics_df.rename(columns=new_names, inplace=True)#our new names
olympics_df.rename(columns={'Country':'Tag'}, inplace=True)
to_drop = ['Gold','Silver','Bronze','Gold.1','Total','Silver.1','Bronze.1','# Games','Gold.2','Silver.2','Bronze.2','Total.1']
olympics_df.drop(to_drop, inplace=True, axis=1)
olympics_df['Combined total']=olympics_df['Summer Olympics']+ olympics_df['Winter Olympics']#Combined total is of both the winter and summer olympics.
#add data frames winter +summer olympics
c = []
for i in range (0, len(olympics_df)):
    c.append(olympics_df['Tag'][i].split(" ")[0])
c
olympics_df['Tag']=pd.DataFrame(c)
olympics_df.head(20)

            Tag  Summer Olympics  Winter Olympics  Combined total
0   Afghanistan               13                0              13
1       Algeria               12                3              15
2     Argentina               23               18              41
3       Armenia                5                6              11
4   Australasia                2                0               2
5     Australia               25               18              43
6       Austria               26               22              48
7    Azerbaijan                5                5              10
8       Bahamas               15                0              15
9       Bahrain                8                0               8
10     Barbados               11                0              11
11      Belarus                5                6              11
12      Belgium               25               20              45
13      Bermuda               17                7              24
14      Bohemia                3                0               3
15     Botswana                9                0               9
16       Brazil               21                7              28
17      British                1                0               1
18     Bulgaria               19               19              38
19      Burundi                5                0               5